# Generated by Django 3.0.6 on 2020-07-31 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startD', models.DateField(default=django.utils.timezone.now)),
                ('endD', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('payment', 'By Payment'), ('location', 'By Location'), ('counselor', 'By Counselor'), ('course', 'By Course')], default='Choose Type', max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifiedId', models.PositiveIntegerField()),
                ('firstName', models.CharField(max_length=14)),
                ('lastName', models.CharField(max_length=18)),
                ('counselor', models.CharField(max_length=24)),
                ('course', models.CharField(max_length=32)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='VerifiedId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
