# Generated by Django 3.0.6 on 2020-07-12 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200701_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Reports'},
        ),
    ]
