# Generated by Django 3.0.6 on 2020-08-23 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=64, verbose_name='Company')),
                ('contactName', models.CharField(max_length=64, verbose_name='Contact Name')),
                ('contactEmail', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('companyAddress', models.CharField(max_length=64, verbose_name='Company Address')),
            ],
            options={
                'verbose_name': 'jobs_client',
                'verbose_name_plural': 'jobs_clients',
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Course')),
                ('location', models.CharField(max_length=64, verbose_name='Location')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('postedDate', models.DateField(auto_now_add=True, verbose_name='Posted Date')),
                ('position', models.CharField(max_length=64, verbose_name='Position')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='jobs.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_company', to='jobs.Client')),
            ],
            options={
                'permissions': (('company_user', 'Company User'),),
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting', to='jobs.Posting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_apply', 'Can Apply'),),
            },
        ),
    ]
