# Generated by Django 3.0.6 on 2020-08-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='postedDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
