# Generated by Django 3.0.6 on 2020-08-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('jobs', '0002_auto_20200813_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(max_length=64, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='client',
            name='companyAddress',
            field=models.CharField(max_length=64, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contactEmail',
            field=models.EmailField(max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contactName',
            field=models.CharField(max_length=64, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='location',
            field=models.CharField(max_length=64, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='position',
            field=models.CharField(max_length=64, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='postedDate',
            field=models.DateField(auto_now_add=True, verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Course'),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.UserProfile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_company', to='jobs.Client')),
            ],
        ),
    ]
