# Generated by Django 3.0.6 on 2020-08-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200814_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'permissions': (('can_apply', 'Can Apply'),)},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'jobs_client', 'verbose_name_plural': 'jobs_clients'},
        ),
        migrations.AlterModelOptions(
            name='companyuser',
            options={'permissions': (('company_user', 'Company User'),)},
        ),
    ]
