# Generated by Django 3.0.6 on 2020-07-31 18:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ssn', models.CharField(max_length=9)),
                ('zipcode', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=30)),
                ('country', models.CharField(default='United States of America', max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('cellPhone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=30)),
                ('location', models.CharField(blank=True, help_text='Not Required', max_length=30)),
                ('refer', models.CharField(blank=True, help_text='Not Required', max_length=30)),
                ('sources', models.CharField(blank=True, help_text='Not Required', max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['created_on'],
            },
        ),
    ]
