# Generated by Django 3.0.6 on 2020-08-13 18:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ssn', models.CharField(help_text='example:123-45-6789 (dash is included automatically', max_length=11)),
                ('zipcode', models.CharField(help_text='example: 99999', max_length=10)),
                ('homeAddress', models.CharField(max_length=64)),
                ('country', models.CharField(default='United States of America', max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('cellPhone', phonenumber_field.modelfields.PhoneNumberField(help_text='example: +12125552368', max_length=128, region=None)),
                ('email', models.EmailField(max_length=30)),
                ('location', models.CharField(choices=[('southplainfield-g', 'South Plainfield G'), ('southplainfield-b', 'South Plainfield B'), ('southplainfield-c', 'South Plainfield C'), ('southplainfield-d', 'South Plainfield D'), ('southplainfield-e', 'South Plainfield E'), ('southplainfield-a', 'South Plainfield A'), ('southplainfield-h', 'South Plainfield H'), ('southplainfield-f', 'South Plainfield F'), ('fairfield-e', 'Fairfield E'), ('fairfield-a', 'Fairfield A'), ('fairfield-b', 'Fairfield B'), ('fairfield-c', 'Fairfield C'), ('fairfield-d', 'Fairfield D'), ('eatontown-a', 'Eatontown A'), ('eatontown-b', 'Eatontown B'), ('eatontown-c', 'Eatontown C'), ('eatontown-d', 'Eatontown D'), ('eatontown-e', 'Eatontown E')], default='southplainfield-g', max_length=30)),
                ('refer', models.CharField(blank=True, help_text='Not Required', max_length=30)),
                ('sources', models.CharField(blank=True, help_text='Not Required', max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['created_on'],
            },
        ),
    ]
