# Generated by Django 3.0.6 on 2020-08-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiawdp', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter the course name.', max_length=128)),
                ('subject', models.CharField(choices=[('medical_tech', 'Medical Tech'), ('dental', 'Detal'), ('programming', 'Computer Programming'), ('security', 'Security'), ('database', 'Database'), ('project_management', 'Project Management')], max_length=32)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('southplainfield-g', 'South Plainfield G'), ('southplainfield-b', 'South Plainfield B'), ('southplainfield-c', 'South Plainfield C'), ('southplainfield-d', 'South Plainfield D'), ('southplainfield-e', 'South Plainfield E'), ('southplainfield-a', 'South Plainfield A'), ('southplainfield-h', 'South Plainfield H'), ('southplainfield-f', 'South Plainfield F'), ('fairfield-e', 'Fairfield E'), ('fairfield-a', 'Fairfield A'), ('fairfield-b', 'Fairfield B'), ('fairfield-c', 'Fairfield C'), ('fairfield-d', 'Fairfield D'), ('eatontown-a', 'Eatontown A'), ('eatontown-b', 'Eatontown B'), ('eatontown-c', 'Eatontown C'), ('eatontown-d', 'Eatontown D'), ('eatontown-e', 'Eatontown E')], max_length=32)),
                ('wiawdp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='WIAWDP', to='wiawdp.WIAWDP')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-created'],
                'permissions': (('can_list_courses', 'List All The Courses'),),
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.UserProfile')),
            ],
        ),
    ]
