# Generated by Django 3.0.6 on 2020-06-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created'], 'permissions': (('can_list_courses', 'List All The Courses'),), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
