# Generated by Django 3.0.6 on 2020-06-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_list_employees', 'List All Employees'),)},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('administration', 'Administration'), ('admission', 'Admission'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('humanresources', 'Human Resources'), ('careerservices', 'Career Services'), ('finance', 'Finannce'), ('staff', 'Staff'), ('faculty', 'Faculty')], max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('instructor_contractor', 'Adjunct Instructor'), ('careerservices', 'Career Services'), ('technology', 'Technology'), ('staff', 'Staff'), ('humanresources', 'Human Resources'), ('admission', 'Admission')], max_length=32),
        ),
    ]
