# Generated by Django 3.0.6 on 2020-05-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pclients', '0003_auto_20200528_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddress',
            name='ext_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pclient',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('None', 'None')], default='None', max_length=8),
        ),
    ]
