# Generated by Django 3.0.6 on 2020-05-31 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pclients', '0004_auto_20200528_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pclient',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'pclient'},
        ),
    ]
