# Generated by Django 3.0.6 on 2020-07-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20200623_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'permissions': (('can_view_pending_schedule', 'Can View Pending Schedule'), ('can_approve_schedule', 'Can Approve Schedule'))},
        ),
    ]
